import { FoodItem } from "../../types";
import c1 from "../img/c1.png";
import c2 from "../img/c2.png";
import c3 from "../img/c3.png";
import c6 from "../img/c6.png";
import c7 from "../img/c7.png";
import cu1 from "../img/cu1.png";
import cu2 from "../img/cu2.png";
import cu3 from "../img/cu3.png";
import cu4 from "../img/cu4.png";
import cu5 from "../img/cu5.png";
import cu6 from "../img/cu6.png";
import d1 from "../img/d1.png";
import d2 from "../img/d2.png";
import d5 from "../img/d5.png";
import d7 from "../img/d7.png";
import fi1 from "../img/fi1.png";
import fi2 from "../img/fi2.png";
import fi3 from "../img/fi3.png";
import fi4 from "../img/fi4.png";
import r1 from "../img/r1.png";
import r2 from "../img/r2.png";
import r3 from "../img/r3.png";
import r4 from "../img/r4.png";
import r5 from "../img/r5.png";

/** Local Abakaliki Nigerian menu — used when Firestore is empty. */
export const abakalikiMenu: FoodItem[] = [
  {
    id: 1001,
    title: "Party Jollof",
    description: "Smoky Abakaliki-style party jollof with chicken",
    price: "3500",
    imageURL: r1,
    calories: "640",
    qty: "40",
    category: "rice",
  },
  {
    id: 1002,
    title: "Ofada Rice & Ayamase",
    description: "Local ofada with spicy green pepper stew",
    price: "4200",
    imageURL: r2,
    calories: "710",
    qty: "30",
    category: "rice",
  },
  {
    id: 1003,
    title: "Native Fried Rice",
    description: "Vegetables, liver & prawns the Eastern way",
    price: "3800",
    imageURL: r3,
    calories: "590",
    qty: "35",
    category: "rice",
  },
  {
    id: 1004,
    title: "White Rice & Stew",
    description: "Soft rice with rich tomato stew & fish",
    price: "2800",
    imageURL: r4,
    calories: "520",
    qty: "50",
    category: "rice",
  },
  {
    id: 1005,
    title: "Coconut Rice",
    description: "Fragrant coconut rice with grilled chicken",
    price: "3600",
    imageURL: r5,
    calories: "610",
    qty: "28",
    category: "rice",
  },
  {
    id: 1006,
    title: "Egusi Soup",
    description: "Thick egusi with assorted meat & stockfish",
    price: "4500",
    imageURL: cu1,
    calories: "780",
    qty: "40",
    category: "soups",
  },
  {
    id: 1007,
    title: "Oha Soup",
    description: "Classic Ebonyi oha with cocoyam thickener",
    price: "4800",
    imageURL: cu2,
    calories: "720",
    qty: "35",
    category: "soups",
  },
  {
    id: 1008,
    title: "Nsala (White Soup)",
    description: "Light catfish nsala — Abakaliki favourite",
    price: "5000",
    imageURL: cu3,
    calories: "650",
    qty: "25",
    category: "soups",
  },
  {
    id: 1009,
    title: "Okra Soup",
    description: "Draw soup with stockfish & fresh okra",
    price: "4000",
    imageURL: cu4,
    calories: "580",
    qty: "30",
    category: "soups",
  },
  {
    id: 1010,
    title: "Afang Soup",
    description: "Waterleaf & afang with periwinkle",
    price: "4700",
    imageURL: cu5,
    calories: "700",
    qty: "28",
    category: "soups",
  },
  {
    id: 1011,
    title: "Bitterleaf Soup",
    description: "Traditional onugbu with cow leg",
    price: "4300",
    imageURL: cu6,
    calories: "690",
    qty: "30",
    category: "soups",
  },
  {
    id: 1012,
    title: "Pounded Yam & Egusi",
    description: "Smooth swallow with generous egusi",
    price: "5200",
    imageURL: cu1,
    calories: "890",
    qty: "40",
    category: "swallows",
  },
  {
    id: 1013,
    title: "Fufu & Oha",
    description: "Soft cassava fufu with Ebonyi oha",
    price: "4800",
    imageURL: cu2,
    calories: "820",
    qty: "40",
    category: "swallows",
  },
  {
    id: 1014,
    title: "Eba & Nsala",
    description: "Garri eba with steaming white soup",
    price: "4500",
    imageURL: cu3,
    calories: "800",
    qty: "35",
    category: "swallows",
  },
  {
    id: 1015,
    title: "Semo & Okra",
    description: "Semolina swallow with okra draw soup",
    price: "4200",
    imageURL: cu4,
    calories: "760",
    qty: "35",
    category: "swallows",
  },
  {
    id: 1016,
    title: "Abakaliki Suya",
    description: "Spicy beef suya with onions & tomatoes",
    price: "2500",
    imageURL: c1,
    calories: "480",
    qty: "60",
    category: "grills",
  },
  {
    id: 1017,
    title: "Grilled Chicken",
    description: "Charcoal-grilled half chicken, pepper sauce",
    price: "5500",
    imageURL: c3,
    calories: "720",
    qty: "40",
    category: "grills",
  },
  {
    id: 1018,
    title: "Chicken BBQ Wings",
    description: "Sticky local BBQ wings",
    price: "3200",
    imageURL: c2,
    calories: "540",
    qty: "45",
    category: "grills",
  },
  {
    id: 1019,
    title: "Asun",
    description: "Peppered goat meat — night special",
    price: "4000",
    imageURL: c6,
    calories: "610",
    qty: "35",
    category: "grills",
  },
  {
    id: 1020,
    title: "Peppered Gizzard",
    description: "Crispy gizzard in spicy sauce",
    price: "2800",
    imageURL: c7,
    calories: "420",
    qty: "50",
    category: "grills",
  },
  {
    id: 1021,
    title: "Catfish Pepper Soup",
    description: "Fresh catfish in aromatic pepper broth",
    price: "4500",
    imageURL: fi3,
    calories: "380",
    qty: "30",
    category: "pepper-soup",
  },
  {
    id: 1022,
    title: "Goat Meat Pepper Soup",
    description: "Rich goat meat pepper soup",
    price: "4000",
    imageURL: fi2,
    calories: "410",
    qty: "35",
    category: "pepper-soup",
  },
  {
    id: 1023,
    title: "Assorted Pepper Soup",
    description: "Offals & meat in spicy broth",
    price: "3800",
    imageURL: fi4,
    calories: "450",
    qty: "30",
    category: "pepper-soup",
  },
  {
    id: 1024,
    title: "Fried Tilapia",
    description: "Crispy whole tilapia with sauce",
    price: "5000",
    imageURL: fi1,
    calories: "560",
    qty: "25",
    category: "fish",
  },
  {
    id: 1025,
    title: "Zobo",
    description: "Chilled hibiscus drink with ginger",
    price: "800",
    imageURL: d1,
    calories: "90",
    qty: "80",
    category: "drinks",
  },
  {
    id: 1026,
    title: "Chapman",
    description: "Classic Nigerian mocktail",
    price: "1500",
    imageURL: d2,
    calories: "160",
    qty: "60",
    category: "drinks",
  },
  {
    id: 1027,
    title: "Fresh Palm Wine",
    description: "Fresh local palm wine (when in season)",
    price: "1000",
    imageURL: d7,
    calories: "120",
    qty: "40",
    category: "drinks",
  },
  {
    id: 1028,
    title: "Kunu",
    description: "Millet kunu Aya",
    price: "700",
    imageURL: d5,
    calories: "110",
    qty: "50",
    category: "drinks",
  },
];

export const restaurantInfo = {
  name: "Chronicles",
  tagline: "Taste of Abakaliki",
  city: "Abakaliki",
  state: "Ebonyi State",
  country: "Nigeria",
  address: "No. 12 Ogoja Road, Abakaliki, Ebonyi State",
  phone: "+234 803 000 0000",
  email: "hello@chronicles.ng",
  hours: [
    { day: "Monday – Thursday", time: "10:00 AM – 9:00 PM" },
    { day: "Friday – Saturday", time: "10:00 AM – 11:00 PM" },
    { day: "Sunday", time: "12:00 PM – 8:00 PM" },
  ],
};
